1. Pull total number of orders that were completed on 18th March 2023
SELECT COUNT(distinct order_id) 
FROM sales 
WHERE date = "03-18-2023";

2. Pull total number of orders that were completed on 18th March 2023 
with the first name ‘John’ and last name ‘Doe’

SELECT COUNT(distinct s.order_id) 
FROM sales as s 
Left JOIN  customers as c ON s.customer_id = c.customer_id
WHERE s.date = "03-18-2023" 
    AND c.first_name = 'Jogn' AND c.last_name = 'Doe';

3. Pull total number of customers that purchased in January 2023 and the average amount spend per customer
SELECT COUNT(distinct customer_id), 
    SUM(total_customer_revenue) as average_spend_per_customer
FROM (
    SELECT customer_id, SUM(revenue) as total_customer_revenue
    FROM sales
    WHERE CAST(date AS string) like “01-%-2022”
    GROUP BY customer_id
);

4. Pull the departments that generated less than $600 in 2022
SELECT i.department, SUM(s.revenue) as sales
FROM sales as s 
JOIN items as i ON s.item_id = i.item_id
WHERE CAST(s.date AS string) like “%-%-2022” 
GROUP BY i.department
HAVING sales <600;

5. What is the most and least revenue we have generated by an order
SELECT MIN(revenue) as min_revenue, 
    MAX(revenue) as max_revenue
FROM sales;


6. What were the orders that were purchased in our most lucrative order
SELECT s.order_id, s.item_id, i.item_name
FROM sales s JOIN item i ON s.item_id = i.item_id
WHERE s.order_id = (
    SELECT order_id 
    FROM sales 
    ORDER BY revenue DESC 
    LIMIT 1
)